-- ====================================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE: HISTORIAL MÉDICO / ADMIN CLÍNICO
-- ====================================================================

-- Habilitar extensión para búsqueda de texto
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. TABLA: PACIENTES (patients)
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expediente TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    sexo TEXT CHECK (sexo IN ('Femenino', 'Masculino', 'Otro')),
    edad INTEGER,
    estado_civil TEXT,
    ocupacion TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_patients_expediente ON public.patients (expediente);
CREATE INDEX IF NOT EXISTS idx_patients_nombre ON public.patients USING gin (nombre gin_trgm_ops);
-- Si no está instalada pg_trgm, índice btree estándar:
CREATE INDEX IF NOT EXISTS idx_patients_created_at ON public.patients (created_at DESC);

-- 2. TABLA: EXPEDIENTES / CONSULTAS CLÍNICAS (clinical_records)
CREATE TABLE IF NOT EXISTS public.clinical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by UUID REFERENCES auth.users(id),

    -- 1. Motivo y Enfermedad actual
    motivo_consulta TEXT,
    enfermedad_actual TEXT,

    -- 2. Antecedentes Personales Patológicos (AP)
    ap_diabetes BOOLEAN DEFAULT FALSE,
    ap_hta BOOLEAN DEFAULT FALSE,
    ap_cardiovascular BOOLEAN DEFAULT FALSE,
    ap_respiratoria BOOLEAN DEFAULT FALSE,
    ap_renal BOOLEAN DEFAULT FALSE,
    ap_alergias TEXT,
    ap_otros TEXT,

    -- 3. Antecedentes Personales No Patológicos (ANP)
    anp_alimentacion TEXT,
    anp_actividad_fisica TEXT,
    anp_alcohol TEXT,
    anp_tabaco TEXT,
    anp_drogas TEXT,
    anp_vacunacion TEXT,

    -- 4. Gineco-Obstétricos (GO)
    go_menarca NUMERIC,
    go_fum DATE,
    go_ciclo TEXT,
    go_embarazos NUMERIC,
    go_partos NUMERIC,
    go_cesareas NUMERIC,
    go_abortos NUMERIC,

    -- 5. Antecedentes Familiares (AF)
    af_diabetes BOOLEAN DEFAULT FALSE,
    af_hta BOOLEAN DEFAULT FALSE,
    af_cancer BOOLEAN DEFAULT FALSE,
    af_hereditarias TEXT,
    af_otros TEXT,

    -- 6. Revisión por Sistemas (RS)
    rs_general TEXT,
    rs_cardiovascular TEXT,
    rs_respiratorio TEXT,
    rs_digestivo TEXT,
    rs_genitourinario TEXT,
    rs_neurologico TEXT,
    rs_musculoesqueletico TEXT,

    -- 7. Signos Vitales (SV)
    sv_ta TEXT,
    sv_fc TEXT,
    sv_fr TEXT,
    sv_temp TEXT,
    sv_peso NUMERIC,
    sv_talla NUMERIC,
    sv_imc NUMERIC,

    -- 8. Exploración Física (EF)
    ef_cabeza_cuello TEXT,
    ef_torax TEXT,
    ef_abdomen TEXT,
    ef_extremidades TEXT,
    ef_neurologico TEXT,

    -- 9. Diagnósticos, Estudios y Plan
    estudios TEXT,
    diagnosticos TEXT,
    plan TEXT,
    observaciones TEXT
);

CREATE INDEX IF NOT EXISTS idx_records_patient_id ON public.clinical_records (patient_id);
CREATE INDEX IF NOT EXISTS idx_records_created_at ON public.clinical_records (created_at DESC);

-- 3. POLÍTICAS DE SEGURIDAD (Row Level Security - RLS)
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_records ENABLE ROW LEVEL SECURITY;

-- Políticas para usuarios autenticados
CREATE POLICY "Permitir select a usuarios autenticados en patients"
    ON public.patients FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir insert a usuarios autenticados en patients"
    ON public.patients FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir update a usuarios autenticados en patients"
    ON public.patients FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir delete a usuarios autenticados en patients"
    ON public.patients FOR DELETE TO authenticated USING (true);

CREATE POLICY "Permitir select a usuarios autenticados en clinical_records"
    ON public.clinical_records FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir insert a usuarios autenticados en clinical_records"
    ON public.clinical_records FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Permitir update a usuarios autenticados en clinical_records"
    ON public.clinical_records FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir delete a usuarios autenticados en clinical_records"
    ON public.clinical_records FOR DELETE TO authenticated USING (true);
